messenger4j:
  appSecret: 1b96862375c09ed7ececbcfc4ff8973f
  verifyToken: barclays_bot
  pageAccessToken: EAAbT2pUV3WYBAGSbsISSxJKtZAns982Tx1HC4GInRYLxELyZCbqCXF5bZBn3WnVQw2FZCNBquppTuOuswX6iPZA8AiZBJbljiAkMZCHshrfOMhJNM39axBAsncMhROUTp9GZABt5doZBbDzZBdoIlZAt3ZBAJhTeU2RDl6IkaWzZBgOS7LAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO

